- name: Run OAI CN5G Fed
  hosts: core
  become: yes
  gather_facts: yes
  tasks:
    - name: Copy docker-compose files
      ansible.builtin.synchronize:
        src: ../../docker/cn5g-docker/
        dest: /home/{{ ansible_user }}/cn5g-docker/
        owner: yes
        group: yes
        perms: yes
        recursive: yes

    - name: Run docker-compose
      shell: "docker-compose up -d"
      args:
        chdir: "/home/{{ ansible_user }}/cn5g-docker/"

    - name: List running Docker containers
      ansible.builtin.command:
        cmd: docker ps
      register: docker_ps_output

    - name: Debug output of running Docker containers
      ansible.builtin.debug:
        msg: "{{ docker_ps_output.stdout }}"

    - name: Run apt update and install packages on SPGWU container
      command: docker exec oai-spgwu bash -c "apt update && apt-get install python3-pip -y && apt install -y libnfnetlink-dev libnetfilter-queue-dev"

    - name: Download pip packages on SPGWU container
      command: docker exec oai-spgwu bash -c "pip3 install scapy NetfilterQueue"

    
